### ISSUE TITLE
Tier 1 - Game Logic: Player Tracking

### ISSUE THREAD

**Issue by sdokus** [Cross-Wars/cross-wars#37]
- [x] The color the player chooses in the Landing Page is the color their guesses are in
- [x] When they guess a word correctly, the background of that cell changes to their selected color on all screens
- [x] The players score is tracked using localStorage, and updated with every correct word
- [x] All players can see the correct color for each player
